version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        build:
            context: ./docker/postgres
        container_name: vitorlbarroso_sgbr
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: vitorlbarroso_test_sgbr
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
